### ISSUE TITLE
NullPointerException: Rendering Block Entity

### ISSUE THREAD

**Issue by TomberWolf** [Gollorum/Signpost#12]
Minecraft 1.10.2:

```
Time: 4/4/17 4:14 PM
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
	at gollorum.signpost.blocks.PostPostTile.calcRot1(PostPostTile.java:145)
	at gollorum.signpost.render.PostRenderer.renderTileEntityAt(PostRenderer.java:29)
	at gollorum.signpost.render.PostRenderer.func_180535_a(PostRenderer.java:13)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:169)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:142)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:999)
	at shadersmod.client.ShadersRender.renderShadowMap(ShadersRender.java:361)
	at shadersmod.client.Shaders.beginRender(Shaders.java:4051)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1545)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1345)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at gollorum.signpost.blocks.PostPostTile.calcRot1(PostPostTile.java:145)
	at gollorum.signpost.render.PostRenderer.renderTileEntityAt(PostRenderer.java:29)
	at gollorum.signpost.render.PostRenderer.func_180535_a(PostRenderer.java:13)

-- Block Entity Details --
Details:
	Name: SignpostPostTile // gollorum.signpost.blocks.PostPostTile
	Block type: ID #1492 (tile.signpost:postjungle // gollorum.signpost.blocks.PostPost)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-45604,68,1495), Chunk: (at 12,4,7 in -2851,93; contains blocks -45616,0,1488 to -45601,255,1503), Region: (-90,2; contains chunks -2880,64 to -2849,95, blocks -46080,0,1024 to -45569,255,1535)
	Actual block type: ID #1492 (tile.signpost:postjungle // gollorum.signpost.blocks.PostPost)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:169)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:142)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:999)
	at shadersmod.client.ShadersRender.renderShadowMap(ShadersRender.java:361)
	at shadersmod.client.Shaders.beginRender(Shaders.java:4051)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1545)
```

**Comment by Gollorum** [comment]
Thank you. A fix will be online soon. Did you deactivate teleportation in the config file when it crashed?

**Comment by TomberWolf** [comment]
Yes, I did.
I just want to use them as normal wayposts.

**Comment by Gollorum** [comment]
Ok, thanks. In that case, the update schould fix it. It is already online.

**Comment by TomberWolf** [comment]
It does! Thanks!
