### ISSUE TITLE
New players cannot join a server after early players have played for some time on the world.

### ISSUE THREAD

**Issue by Velorx** [Gollorum/Signpost#91]
As the title explains it, at least that is what I observed because none of new player were able to join the server.

**Error Log:**

[20:46:14] [Server thread/INFO]: [player] joined the game
[20:46:14] [Server thread/ERROR]: Exception caught during firing event: Cannot read field "name" because "entry" is null
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class gollorum.signpost.minecraft.worldgen.WaystoneDiscoveryEventListener onWatchChunk(Lnet/minecraftforge/event/world/ChunkWatchEvent$Watch;)V
java.lang.NullPointerException: Cannot read field "name" because "entry" is null
	at TRANSFORMER/signpost@1.18.1-2.00.4/gollorum.signpost.WaystoneLibrary.getData(WaystoneLibrary.java:103)
	at TRANSFORMER/signpost@1.18.1-2.00.4/gollorum.signpost.minecraft.worldgen.WaystoneDiscoveryEventListener.onWatchChunk(WaystoneDiscoveryEventListener.java:45)
	at net.minecraftforge.eventbus.ASMEventHandler_38_WaystoneDiscoveryEventListener_onWatchChunk_Watch.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@39.0.58/net.minecraftforge.event.ForgeEventFactory.fireChunkWatch(ForgeEventFactory.java:692)
	at TRANSFORMER/forge@39.0.58/net.minecraftforge.event.ForgeEventFactory.fireChunkWatch(ForgeEventFactory.java:700)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ChunkMap.m_183754_(ChunkMap.java:779)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ChunkMap.m_140192_(ChunkMap.java:923)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ChunkMap.m_140199_(ChunkMap.java:1045)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ServerChunkCache.m_8463_(ServerChunkCache.java:458)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1551)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1534)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157575_(PersistentEntitySectionManager.java:135)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.entity.PersistentEntitySectionManager.addEntityWithoutEvent(PersistentEntitySectionManager.java:98)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.entity.PersistentEntitySectionManager.addNewEntityWithoutEvent(PersistentEntitySectionManager.java:76)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ServerLevel.m_8853_(ServerLevel.java:827)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ServerLevel.m_8834_(ServerLevel.java:771)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:190)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:138)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:125)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10050_(ServerLoginPacketListenerImpl.java:69)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.network.Connection.m_129483_(Connection.java:229)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

[20:46:14] [Server thread/ERROR]: Couldn't place player in world
java.lang.NullPointerException: Cannot read field "name" because "entry" is null
	at gollorum.signpost.WaystoneLibrary.getData(WaystoneLibrary.java:103) ~[signpost-1.18.1-2.00.4.jar%2364!/:1.18.1-2.00.4]
	at gollorum.signpost.minecraft.worldgen.WaystoneDiscoveryEventListener.onWatchChunk(WaystoneDiscoveryEventListener.java:45) ~[signpost-1.18.1-2.00.4.jar%2364!/:1.18.1-2.00.4]
	at net.minecraftforge.eventbus.ASMEventHandler_38_WaystoneDiscoveryEventListener_onWatchChunk_Watch.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.event.ForgeEventFactory.fireChunkWatch(ForgeEventFactory.java:692) ~[forge-1.18.1-39.0.58-universal.jar%2375!/:?]
	at net.minecraftforge.event.ForgeEventFactory.fireChunkWatch(ForgeEventFactory.java:700) ~[forge-1.18.1-39.0.58-universal.jar%2375!/:?]
	at net.minecraft.server.level.ChunkMap.m_183754_(ChunkMap.java:779) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.level.ChunkMap.m_140192_(ChunkMap.java:923) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.level.ChunkMap.m_140199_(ChunkMap.java:1045) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8463_(ServerChunkCache.java:458) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1551) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1534) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157575_(PersistentEntitySectionManager.java:135) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.addEntityWithoutEvent(PersistentEntitySectionManager.java:98) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.addNewEntityWithoutEvent(PersistentEntitySectionManager.java:76) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.level.ServerLevel.m_8853_(ServerLevel.java:827) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.level.ServerLevel.m_8834_(ServerLevel.java:771) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:190) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:138) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:125) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10050_(ServerLoginPacketListenerImpl.java:69) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:229) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[20:46:14] [Server thread/INFO]: [player] lost connection: Invalid player data
[20:46:14] [Server thread/INFO]: [player] left the game

**Comment by Gollorum** [comment]
Sorry for the long wait, I didn't find the time to test my fix.
Version 2.00.5 should solve the issue

Thanks for reporting it
